### ISSUE TITLE
naming conflicts on ZSH

### ISSUE THREAD

**Issue by antony** [olistic/warriorjs#117] opened 2018-05-17 16:25 UTC
In ZSH, shell interpretation causes `warriorjs` not to run after the initial profile is created.

# Environment

## System:
 - OS: Linux 4.13 Ubuntu 17.10 (Artful Aardvark)
 - CPU: x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
 - Memory: 243.71 MB / 7.70 GB
 - Container: Yes
 - Shell: 5.2 - /usr/bin/zsh
## Binaries:
 - Node: 9.5.0 - ~/.nvm/versions/node/v9.5.0/bin/node
 - npm: 5.6.0 - ~/.nvm/versions/node/v9.5.0/bin/npm
## npmGlobalPackages:
 - @warriorjs/cli: 0.3.0

# Steps to reproduce

1. Run warriorjs for the first time.
2. Edit Player.js as suggested
3. Run warriorjs again

# Expected Behavior

warriorjs runs a second time

# Actual Behavior

zsh interprets `warriorjs` as `cd warriorjs`, as there is now a directory called `warriorjs` created by the CLI.

**Comment by olistic** [comment] 2018-05-17 17:16
Hello @antony, this is a duplicate of #95 (related to the `AUTO_CD` option of zsh). Closing this, please comment there if you have any suggestion. Thanks!

**Closed by olistic** 2018-05-17 17:16 UTC
Labels: pkg: cli, type: duplicate
