### ISSUE TITLE
CLI is not running because of an error.

### ISSUE THREAD

**Issue by nicolaelitvac** [olistic/warriorjs#109] opened 2018-05-16 07:08 UTC
# Steps to reproduce
Install warriorjs:
`$ npm install --global @warriorjs/cli`
Run worriorjs:
`$ warriorjs`
Error in the console:
```bash
/usr/local/lib/node_modules/@warriorjs/cli/lib/cli.js:24
async function run(args) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@warriorjs/cli/bin/warriorjs.js:3:1)
```
## System:
 - OS: macOS High Sierra 10.13.4
 - CPU: x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
 - Memory: 2.11 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 6.11.2 - /usr/local/bin/node
 - npm: 6.0.0 - /usr/local/bin/npm

**Comment by olistic** [comment] 2018-05-16 12:39
Hello @nicolaelitvac! This is a duplicate of #80. WarriorJS [requires Node >= 8](https://warrior.js.org/docs/en/set-up.html) to work.

**Closed by olistic** 2018-05-16 12:39 UTC
Labels: pkg: cli, type: duplicate
